### ISSUE TITLE
Missing past type efficacies

### ISSUE THREAD

**Issue by KidsDontPlay** [veekun/pokedex#303] opened 2020-05-03 14:01 UTC
Some type efficacies changed over the generations.

Source: https://bulbapedia.bulbagarden.net/wiki/Type/Type_chart#Changes

**Comment by venustoise** [comment] 2020-06-16 22:13
Yes, only two times when new types were introduced. Also Pokémon base stats and base exp yield have changed between the last generations, and the abilities too. Catch rate has also changed between version groups starting from ancient Red/Blue and Yellow version (with different held item if transferred to GSC for Kadabra, Dragonair, Dragonite and Starter Pikachu [source:bulbapedia], but this last one is also the only major form missing...). Colors and shapes have sometimes changed and also been associated to forms instead of species.
The thing is that veekun actually has all the data (except shapes/colors for different, not default forms) in the old versions of csv files, in particular the latest for each Generation (V->7 Feb 2013/ VI->16 Oct 2016), with last gen.4 data available in the old repository zzz-pokedex.git on git.veekun.com. I hope this post can help @magical to further improve the already best Pokémon db over Internet, this:)

**Comment by magical** [comment] 2020-06-17 20:51
Duplicate of #107

**Closed by magical** 2020-06-17 20:51 UTC
