### ISSUE TITLE
Weezing abilities

### ISSUE THREAD

**Issue by Naramsim** [veekun/pokedex#322] opened 2020-10-15 10:05 UTC
Hello, this references an [issue](https://github.com/PokeAPI/pokedex/issues/13) over at Pokeapi opened by @SDM0. It seems that Weezing(`110`) has two abilities (`Levitate` and `Neutralizing Gas`) and one hidden (`Stench`). Currently, in Veekun data there is only `Levitate`. 

I checked on Bulbapedia and Pokemon.com and the 3 abilities seem to be legit. 

Do you think this data should be incorporated? Would you like a PR?

**Comment by magical** [comment] 2020-10-15 23:20
The Neutralizing Gas ability was added in Sword/Shield. Likewise, although Stench existed before then, Weezing and Koffing had no hidden ability before Sword/Shield.

So this is a duplicate of #284

**Closed by magical** 2020-10-15 23:20 UTC
