### ISSUE TITLE
Some mons missing USUM tutor moves

### ISSUE THREAD

**Issue by unlightednetting** [veekun/pokedex#306] opened 2020-05-25 16:43 UTC
Seems similiar to issue #223 but is a half different topic.

After comparing the tutor moves for Bulbasaur between the veekun page and bulbapedia, I noticed the trend that the tutor moves from Ultra Sun and Ultra Moon were missing from veekun. After checking with Smogodon as well, it would appear that either their pages are incorrectly adding moves, or that veekun is missing tutor moves that were not in S/M and introduced in US/UM

I then compared with eevee(the pokemon) and vaporeon on bulbapedia so that I can check with more than just one mon and one generation, and it seems like they both follow the same trend, with veekun missing the tutor moves listed on that page completely. Not surprising because they didn't have a single tutor move in S/M.

**Comment by magical** [comment] 2020-06-23 04:50
Duplicate of #223

**Closed by magical** 2020-06-23 04:50 UTC
